name: Deploy Frontend

on:
  push:
    branches:
      - feature/* # Trigger build for feature branches
      - master    # Trigger build and deploy when code is pushed to master
  pull_request:
    branches:
      - master # Trigger build when PR is merged into master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mukkipandy/react-test:${{ github.sha }} -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true mukkipandy/react-test:${{ github.sha }} npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Upload deployment package
        uses: actions/upload-artifact@v3
        with:
          name: deploy-package
          path: deploy.zip

  deploy:
    if: github.ref == 'refs/heads/master' && success() # Only on master branch and if build is successful
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          region: ap-south-1
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
